
package vista;

/**
 *
 * @author Admin
 */
public class Calculos extends javax.swing.JFrame {

    
    public Calculos() {
        initComponents();
       
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resBin = new javax.swing.JLabel();
        resFas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c1Modulo = new javax.swing.JTextField();
        c1Arg = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        c2Modulo = new javax.swing.JTextField();
        c2Arg = new javax.swing.JTextField();
        sumar = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        restaurar = new javax.swing.JButton();
        pReal = new javax.swing.JTextField();
        pImag = new javax.swing.JTextField();
        resTrans = new javax.swing.JLabel();
        restaurar2 = new javax.swing.JButton();
        btnz2 = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        transformar1 = new javax.swing.JButton();
        btnz1 = new javax.swing.JButton();
        btnz1Trans = new javax.swing.JButton();
        btnz2Trans = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(451, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de números complejos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 380, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("z1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 20, 23));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("|z|");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Arg(z)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("z2:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 20, 20));

        resBin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        resBin.setForeground(java.awt.Color.white);
        getContentPane().add(resBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 170, 30));

        resFas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        resFas.setForeground(java.awt.Color.white);
        getContentPane().add(resFas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Re(z)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transformar de forma binómica a fasorial");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Im(z)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 40, 20));

        c1Modulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c1Modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ModuloActionPerformed(evt);
            }
        });
        getContentPane().add(c1Modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, -1));

        c1Arg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c1Arg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ArgActionPerformed(evt);
            }
        });
        getContentPane().add(c1Arg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 50, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 0));

        c2Modulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c2Modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ModuloActionPerformed(evt);
            }
        });
        getContentPane().add(c2Modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, -1));

        c2Arg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c2Arg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ArgActionPerformed(evt);
            }
        });
        getContentPane().add(c2Arg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 50, -1));

        sumar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sumar.setText("+");
        sumar.setOpaque(false);
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        getContentPane().add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        multiplicar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        multiplicar.setText("x");
        multiplicar.setOpaque(false);
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        dividir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dividir.setText("/");
        dividir.setOpaque(false);
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        getContentPane().add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 40, -1));

        restaurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        restaurar.setText("Restaurar");
        restaurar.setOpaque(false);
        restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurarActionPerformed(evt);
            }
        });
        getContentPane().add(restaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 110, -1));

        pReal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(pReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, -1));

        pImag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(pImag, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 50, -1));

        resTrans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        resTrans.setForeground(java.awt.Color.white);
        getContentPane().add(resTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, 20));

        restaurar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        restaurar2.setText("Restaurar");
        restaurar2.setOpaque(false);
        restaurar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurar2ActionPerformed(evt);
            }
        });
        getContentPane().add(restaurar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        btnz2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnz2.setText("z2");
        btnz2.setOpaque(false);
        btnz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnz2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 50, 30));

        restar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        restar.setText("-");
        restar.setOpaque(false);
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        getContentPane().add(restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 40, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Resultado en forma fasorial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Resultado en forma binómica:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Resultado en forma fasorial:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 20));

        transformar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        transformar1.setText("Transformar");
        transformar1.setOpaque(false);
        transformar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformar1ActionPerformed(evt);
            }
        });
        getContentPane().add(transformar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btnz1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnz1.setText("z1");
        btnz1.setOpaque(false);
        btnz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnz1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 50, 30));

        btnz1Trans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnz1Trans.setText("z1");
        btnz1Trans.setOpaque(false);
        btnz1Trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnz1TransActionPerformed(evt);
            }
        });
        getContentPane().add(btnz1Trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 50, 30));

        btnz2Trans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnz2Trans.setText("z2");
        btnz2Trans.setOpaque(false);
        btnz2Trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnz2TransActionPerformed(evt);
            }
        });
        getContentPane().add(btnz2Trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 50, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 204));
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/A3E.jpg"))); // NOI18N
        jLabel11.setAutoscrolls(true);
        jLabel11.setMaximumSize(new java.awt.Dimension(451, 350));
        jLabel11.setMinimumSize(new java.awt.Dimension(451, 350));
        jLabel11.setName(""); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(451, 350));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ModuloActionPerformed

    private void c1ArgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ArgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ArgActionPerformed

    private void c2ModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ModuloActionPerformed

    private void c2ArgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ArgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ArgActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
       
        
    }//GEN-LAST:event_dividirActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        
        
    }//GEN-LAST:event_sumarActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        
    }//GEN-LAST:event_multiplicarActionPerformed

    private void restaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurarActionPerformed
    }//GEN-LAST:event_restaurarActionPerformed

    private void btnz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnz2ActionPerformed

        
    }//GEN-LAST:event_btnz2ActionPerformed

    private void restaurar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurar2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_restaurar2ActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
       
    }//GEN-LAST:event_restarActionPerformed

    private void transformar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transformar1ActionPerformed

    private void btnz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnz1ActionPerformed

    private void btnz1TransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnz1TransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnz1TransActionPerformed

    private void btnz2TransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnz2TransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnz2TransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnz1;
    public javax.swing.JButton btnz1Trans;
    public javax.swing.JButton btnz2;
    public javax.swing.JButton btnz2Trans;
    public javax.swing.JTextField c1Arg;
    public javax.swing.JTextField c1Modulo;
    public javax.swing.JTextField c2Arg;
    public javax.swing.JTextField c2Modulo;
    public javax.swing.JButton dividir;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton multiplicar;
    public javax.swing.JTextField pImag;
    public javax.swing.JTextField pReal;
    public javax.swing.JLabel resBin;
    public javax.swing.JLabel resFas;
    public javax.swing.JLabel resTrans;
    public javax.swing.JButton restar;
    public javax.swing.JButton restaurar;
    public javax.swing.JButton restaurar2;
    public javax.swing.JButton sumar;
    public javax.swing.JButton transformar1;
    // End of variables declaration//GEN-END:variables
}
